### ISSUE TITLE
Clicking on "show advanced dism logs" shows an error

### ISSUE THREAD

**Issue by Guarmanda** [CodingWonders/DISMTools#76]
**What is the bug about?**
"show advanced dism logs" in "remove windows image" doesn't work

**How does it happen?**
Click on "remove volume image"
it fails
click on "show advanced dism logs"

**Expected behavior**
dism logs shows

**Screenshots**
![image](https://github.com/CodingWonders/DISMTools/assets/7463055/1a48796f-eebe-4c97-8b01-5d4c17ce40cb)
System.ComponentModel.Win32Exception (0x80004005): Le fichier spécifié est introuvable
   à System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   à System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   à DISMTools.ProgressPanel.LinkLabel1_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   à System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   à System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.Label.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Additional context**
using nyghtly build

**Comment by CodingWonders** [comment]
Thanks for reporting this issue!

Since I can't determine what is causing the problem, I added a `Try` block to the event handle. Because it was throwing an exception, the program will now go to the `Catch` block, which will determine if either Notepad or the log file was not found.

This is available in the latest nightly installer, which I encourage you to download. Perform the same actions as previously, and come back with some answers.

**Comment by CodingWonders** [comment]
The aforementioned PR (for the next preview release) will close this issue, which I see fixed (view comment above). If this still doesn't work right, or if it determines the true cause, create a new issue.
